---
#info:
#  scm-url: "@scm.url@"
#  build-url: "http://travis-ci.org/@env.TRAVIS_REPO_SLUG@/builds/@env.TRAVIS_BUILD_ID@"
#  stage: test
server:
  context-path: "/spring/admin"

management:
  context-path: "/actuator"

spring:
  application:
    name: "@pom.artifactId@"
  boot:
    admin:
#      context-path: /
      url: ${admin.domain}spring/admin
  profiles:
    active:
      - secure

---
spring:
  profiles: insecure

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

---
spring:
  profiles: secure
  boot:
    admin:
      username: "${security.user.name}"       #These two are needed so that the client
      password: "${security.user.password}"   #can register at the protected server api
      client:
        metadata:
          user.name: "${security.user.name}"          #These two are needed so that the server
          user.password:  "${security.user.password}" #can access the proteceted client endpoints

security:
  user:
    name: ${auth.name}
    password: ${auth.pass}


